### PR TITLE
Csv convert for greentable format

### PR DESCRIPTION
**Pull request by djarecka**
I've modified the converter from #19 to work for the examples of the Green Table (for now I only updated `cvs2yaml`.

I've added also an example of cvs files and the header that could be used to run it: `python utils/csv2yaml.py --csv csv_test/GreenTable.csv  --enum csv_test/GreenTable_ValueSet.csv --header csv_test/head.yaml --output csv_test/gt_test.yaml`

The output should look like `csv_test/GreenTable_model.yaml`

I've slightly modified the GreenTable format, see [here](https://docs.google.com/spreadsheets/d/1i8CBHCmbHD-R12VK9ZhYW32NA1unqGZz/edit?usp=sharing&ouid=100266991910557768747&rtpof=true&sd=true) (note that I only worked on `Generate Library`  for now). 
The changes are related to the Value Sets and I've created a new tab: `Generate Library Value Sets` (you can compare with `Value Sets Orig`). The original tab for Value Sets was hard to automatically convert to pandas.DF, so I've added column `Field Name` to remove the titles of previous multiple columns. In order to properly link ValueSets from the `Generate Library` to the values for specific `Field Name`, I assumed that it is either the original `Field Name` from the `Generate Library` tab or `DataType` has the name of the set values, e.g. `ValueSet: barcode name`.

Issues with Value Set that need feedback:
- [ ] I didn't know what to do with the `Code` and `Code general` columns, should this be added to the model?
- [ ] There was sometimes additional info in a column without a name, so I created `Other Info`, not sure what to do with it
- [ ] I didn't know how to interpret columns from `R1/R2 index name`, so for now I removed it

Other issues to discuss:
- [ ] I only added the fields that had "metadata" in the `Identifier/Metadata` column. I assumed that the additional parent class will have the name
- [ ] Some fields had integer as a type, but the example contained floats (when you run the code, you will see errors in the standard output)
- [ ] the examples from `Enriched cell source barcode name` do not match the value sets
- [ ] tried best to automatically split the examples, but probably we should have a better standard way of providing it

Other TODOs (that do not require feedback):
- [ ] add a way to update an existing classes (now I only read a header)

FYI. I will look into the code from the Yale team, I only opened the output quickly and I noticed that there are some things that we discussed done differently, so I decided to finish this PR to help with the discussion.

### CODE REVIEW

**Comment by djarecka** [comment]
@satra @lydiang @patrick-lloyd-ray - if you have time this week you can give me some feedbacks, especially on the issues listed in the PR description. If not we will discuss it later

**Comment by patrick-lloyd-ray** [comment]
@djarecka could you check the integer data types here: https://github.com/brain-bican/metadata-schemas/pull/31 and make sure we are accurate?

**Comment by djarecka** [comment]
@patrick-lloyd-ray - yes I'm planning to check it, I forgot that this is in PR and that's probably better place to add more comments

**Comment by patrick-lloyd-ray** [comment]
> @patrick-lloyd-ray - yes I'm planning to check it, I forgot that this is in PR and that's probably better place to add more comments

Great! Feel free to simply suggest changes directly on the PR.

**Pull request closed without merging**
